baseURL: 'https://karanrn.github.io/'
languageCode: 'en-us'
title: 'Karan Nadagoudar'
theme: "hugo-book"

# Book configuration
disablePathToLower: true
enableGitInfo: true

params:
  BookTheme: "auto"
  BookToC: true
  BookRepo: https://github.com/karanrn/karanrn.github.io
  BookSearch: true

# menu:
#   main:
#   - identifier: about
#     name: about
#     url: /about/
#     params:
#       class: highlight-menu-item
#     weight: -110
#   - identifier: posts
#     name: posts
#     url: /posts/
#     weight: -100
